### ISSUE TITLE
SkiaTexture issues

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.Stride#485] opened 2021-07-19 15:52 UTC
- default format is R16... should be R8...sRGB?
- stops rendering when placed in a patch but nothing connected on its input

**Comment by tebjan** [comment] 2021-07-20 15:24
Couldn't reproduce the rendering stop.

The format looks good, the stride rendering pipeline is per default HDR in linear color space. The SkiaRenderer node renders correctly into that format.

Closing, reopen if the issue persists.

**Closed by tebjan** 2021-07-20 15:24 UTC
Labels: bug
