### ISSUE TITLE
Spout nodes update

### ISSUE THREAD

**Issue by leadedge** [vvvv/VL.Stride#430] opened 2021-02-11 04:48 UTC
Hello everybody,

after contact with Joreg I have had a look at the Spout nodes for compatibility with Spout 2.007 and he suggested to open an issue here.

It seems that these nodes have not been updated since the modifications last year for the Develop branch. Updating to these changes should solve sender texture format and registration problems.

https://github.com/vvvv/vvvv-sdk/pull/293

When you get time to do this I will test again to see if any other changes might be necessary.

Meanwhile I will put a temporary fix within "SpoutPanel" (the popup sender selection dialog) for the sender name of the help patch. After this has run once, the format and registration will be corrected. 

This not ideal because most programs do not implement SpoutPanel, and it would need to be opened separately. Also this will only be for one sender name. But at least it will be something for people who want to use these nodes right away.

**Comment by tebjan** [comment] 2021-02-16 21:20
thanks for the reminder, we'll gladly update to Spout 2.

**Comment by tebjan** [comment] 2021-03-22 11:16
@leadedge @bj-rn the sender is now updated as in #441. does the receiver also need work? or is that optional? is the benefit on the receiver side more an automatic discovery but it works as before if you know the sender name already?

**Comment by bj-rn** [comment] 2021-03-22 11:53
The receiver currently "just" uses the sender name to open the associated shared memory and read the texture description , which works just fine. The downside is that you have to know the available sender(s). Maybe one could add a node listing the available senders for convenience.

**Comment by leadedge** [comment] 2021-03-23 01:53
@tebjan
I would like to test this. Where can I get the preview build? You can use the email on my GitHub page.

**Comment by bj-rn** [comment] 2021-03-23 14:11
@leadedge 
You can download latest stable [here](https://teamcity.vvvv.org/guestAuth/app/rest/builds/id:33946/artifacts/content/vvvv_gamma_2021.3.1_setup.exe) and replace _VL.Stride.Windows.dll_ inside _vvvv_gamma_2021.3.1\lib_ with the one attached.
[VL.Stride.Windows.zip](https://github.com/vvvv/VL.Stride/files/6190223/VL.Stride.Windows.zip)

**Comment by leadedge** [comment] 2021-03-24 01:26
All looks good. I will leave the patch in "SpoutPanel" so that the sender memory map created by older versions is corrected. Keep that in mind when testing the output. Use another receiving application instead of the Spout demo receiver.

For receiver automatic discovery you would find the "Active" sender and connect to that. A list of names would certainly make it easier for the user.

**Comment by tebjan** [comment] 2021-03-24 12:30
@leadedge thanks for testing and glad to hear that it works.

> I will leave the patch in "SpoutPanel" so that the sender memory map created by older versions is corrected. Keep that in mind when testing the output. Use another receiving application instead of the Spout demo receiver.

if you don't mind, I think it would be good to remove that exception when vvvv gamma 2021.4 gets released, which is expected in may. the Spout nodes are still young and it would be better to have the "intended behavior" with the SpoutPanel. it is always a good test case to use the "reference implementation" for checking. we also expect that everyone will move to vvvv gamma 2021.4 soon, which will have the recent update in it.

**Comment by leadedge** [comment] 2021-03-25 00:33
No problems. I will remove it for the next release. This will mean that the sender of older versions with the name "With Love from vvvv" will not show up in the SpoutPanel sender list. Meanwhile for testing you can change the name.

**Comment by joreg** [comment] 2021-07-02 09:55
@leadedge we've finally come to work on this further, i mentioned the recent changes here: https://discourse.vvvv.org/t/receivespouttexture-auto-detect-available-textures-stride-textures-spout/19612/2

if tested this to work with Spout 2.007e. 

i am not exactly sure what you were referring to with "This will mean that the sender of older versions with the name "With Love from vvvv" will not show up in the SpoutPanel sender list." is there still a hack in spout now for working around a vvvv issue?

another question re the list of available senders: am i correctly assuming that every receiving application has to periodically read the "SpoutSenderNames" sharedmem location and see if anything has changed there? or is there some way to get a callback when the list of senders has changed?

**Comment by leadedge** [comment] 2021-07-03 01:35
OK good to hear.

The "SpoutPanel" sender selection program had a patch that detected and registered a sender of the name "With Love from vvvv". After that, it was part of the sender name set and showed up in the list of senders. What I meant was that if you tested your changes to register the VVVV sender using SpoutPanel, you should use a different name to avoid the patch.

In any case, this has been removed for 2.007e. So if it shows up in the list, then all is working OK.

There is no callback set up, so yes you have to check the sender names set in shared memory to find out whether any senders have been added or removed. You need to do this when you display a sender list. If you make such a list only when the program starts, it would become out of date. The same applies for the active sender name.

Instructions for making such a list are documented in [Files > Docs > Sender-list.txt](https://spoutgl-site.netlify.app/#File:Docs/3).

Recently I discovered that the function to retrieve a sender name from the names set had been re-located to the "Spout" class. I have moved it back to the "SpoutSenderNames" class in the [Beta branch](https://github.com/leadedge/Spout2/tree/beta/SPOUTSDK/SpoutGL) and made the function names consistent. Use this branch if you create such a list. I will accumulate more changes in Beta before another release.

**Comment by joreg** [comment] 2021-07-05 13:53
perfect, that explains, thanks. 
so we're considering the current state done and i'm closing this.

**Closed by joreg** 2021-07-05 13:53 UTC
